volumes: 
  db-data:

networks:
  faille-network:
    driver: bridge

services:
  app:
    image: node:23-alpine
    working_dir: /app
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - faille-network
    command: sh -c "npm ci && npm install -g nodemon && nodemon index.js"
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: failleuser
      POSTGRES_PASSWORD: faillepassword
      POSTGRES_DB: failledb
    networks:
      - faille-network