volumes: 
  db-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: failleuser
      POSTGRES_PASSWORD: faillepassword
      POSTGRES_DB: failledb